# Generated by Django 5.2.7 on 2025-10-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_attendance_present_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
        ),
    ]
